language: go
sudo: required
go_import_path: github.com/csi-driver/csi-driver-smb
dist: bionic
services:
  - docker
go:
  - "1.13.9"

before_install:

jobs:
  include:
    - stage: test
      name: "build test"
      script:
        - make verify
        - make smb-windows
        - make container
    - stage: test
      name: "integration test"
      install:
        - GO111MODULE=off go get github.com/rexray/gocsi/csc
        - sudo apt update && sudo apt install cifs-utils procps -y
      script:
        - make
        - make integration-test
