apiVersion: v1
entries:
  csi-driver-smb:
  - apiVersion: v1
    appVersion: v0.2.0
    created: "2020-08-12T01:57:17.022485789Z"
    description: SMB CSI Driver for Kubernetes
    digest: bc0aca4acd74b6c521d85d6d75e1dab22c06dcc9a2e0430abc203a2d5006403d
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.2.0/csi-driver-smb-v0.2.0.tgz
    version: v0.2.0
generated: "2020-08-12T01:57:17.021803482Z"
