apiVersion: v1
entries:
  csi-driver-smb:
  - apiVersion: v1
    appVersion: v0.3.0
    created: "2020-08-19T06:04:00.104700521Z"
    description: SMB CSI Driver for Kubernetes
    digest: ee9e58db6d4a95491e2012c6607126bbff827b9c439e90e9a9798d2a73b0cb22
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.3.0/csi-driver-smb-v0.3.0.tgz
    version: v0.3.0
  - apiVersion: v1
    appVersion: v0.2.0
    created: "2020-08-19T06:04:00.104239817Z"
    description: SMB CSI Driver for Kubernetes
    digest: bc0aca4acd74b6c521d85d6d75e1dab22c06dcc9a2e0430abc203a2d5006403d
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/v0.2.0/csi-driver-smb-v0.2.0.tgz
    version: v0.2.0
  - apiVersion: v1
    appVersion: latest
    created: "2020-08-19T06:04:00.103761712Z"
    description: SMB CSI Driver for Kubernetes
    digest: 726616076e41190988103004a71710847e95deee700f296730f2c264df269d06
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/latest/csi-driver-smb-latest.tgz
    version: latest
generated: "2020-08-19T06:04:00.102958204Z"
